[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
conditional_escrow = "7sWTb3Czsz2vV1RpYpgFtKNkEXGqjcEGCsa31zQKisa5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsc -p tsconfig.build.json && npx mocha dist/tests/**/*.js -t 1000000"
